### ISSUE TITLE
playbook issues with latest ansible

### ISSUE THREAD

**Issue by mightygerm** [XSEDE/CRI_XCBC#17]
The latest dev versions of ansible (2.10) seem to have changed how modules are installed, and removed a lot of modules from the base installation of ansible.

This breaks the xcbc install when running the playbook headnode.yml as the 'nmcli' module no longer seems to be included in the default ansible install.

I have worked around the issue via installing the stable-2.9 branch of ansible instead of the latest sources. A modification of install_anisible.sh to pull that branch does the trick.

It should also be possible to add a command to install nmcli in ansible 2.10, but I am not an ansible expert and I was not able to easily figure out how to do this.

``

**Comment by ECoulter** [comment]
Thanks for the heads up! I've changed to clone the stable-2.9 branch for now. Even the ansible package in the epel has issues with the nmcli module right now. Probably better practice to pin to a specific release branch anyway...
